apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prod-microservice-01
spec:
  template:
    spec:
      containers:
      - image: microservice-01
        env:
        - name: NAME
          value: PRODUCTION
        resources:
          limits:
            memory: 1Gi
            cpu: 2000m            