apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: qa-microservice-01
spec:
  template:
    spec:
      containers:
      - image: microservice-01
        env:
        - name: NAME
          value: QA-OR-STAGE